# Generated by Django 5.1.6 on 2026-05-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Any characters are allowed.', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
