# Generated by Django 5.1.6 on 2026-05-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
