# Generated by Django 5.1.6 on 2026-05-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_optional_message_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
